import clientImg from '../../src/assets/img/client.jpg'
var randomId = require('random-id');
var len = 10;
var pattern = 'c4lEny'
export var event = [
    {
        id: randomId(len, pattern),
        allDay: true,
        end: new Date(new Date().getFullYear(), 0, 1),
        start: new Date(new Date().getFullYear(), 0, 1),
        title: 'Happy New Year',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'worldEvent'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 06:00:00'),
        start: new Date('January 10, 2023 07:00:00'),
        title: 'First Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 13:00:00'),
        start: new Date('January 10, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },

    {
        id: randomId(len, pattern),
        allDay: true,
        end: new Date(new Date().getFullYear(), 0, 1),
        start: new Date(new Date().getFullYear(), 0, 1),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        end: new Date(),
        start: new Date(),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        start: new Date('January 13, 2023 9:00:00'),
        end: new Date('January 13, 2023 11:00:00'),
        title: 'Smart Tech Vietnam 2023',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        start: new Date('January 13, 2023 9:00:00'),
        end: new Date('January 15, 2023 14:00:00'),
        title: 'The Axe & Carlsberg Present MARKHESE',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        start: new Date('January 12, 2023 9:00:00'),
        end: new Date('January 12, 2023 18:00:00'),
        title: 'Color Fiesta season 10: Ruby',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        start: new Date('January 14, 2023 10:00:00'),
        end: new Date('January 15, 2023 2:00:00'),
        title: 'GLOW IN THE DARK PARTY',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: true,
        start: new Date('January 18, 2023 22:00:00'),
        end: new Date('January 18, 2023 23:00:00'),
        title: 'How to Improve Your Memory - Ho Chi Minh City',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 13:00:00'),
        start: new Date('January 10, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 13:00:00'),
        start: new Date('January 10, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 14, 2023 13:00:00'),
        start: new Date('January 14, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 14, 2023 13:00:00'),
        start: new Date('January 14, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 13:00:00'),
        start: new Date('January 10, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 18, 2023 13:00:00'),
        start: new Date('January 18, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'appointment'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 19, 2023 22:00:00'),
        start: new Date('January 19, 2023 23:00:00'),
        title: 'Effective Note-Taking- Ho Chi Minh City',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 17, 2023 7:00:00'),
        start: new Date('January 17, 2023 8:00:00'),
        title: 'Speed Reading Crash Course - Ho Chi Minh City',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 18, 2023 19:00:00'),
        start: new Date('January 18, 2023 22:00:00'),
        title: 'YEP - PMI CHAPTER VN STUDY GROUP ++',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 1, 2023 9:00:00'),
        start: new Date('February 1, 2023 17:00:00'),
        title: 'Corporate Finance Masterclass',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 9, 2023 13:00:00'),
        start: new Date('February 9, 2023 16:00:00'),
        title: '2023 5th Asia Pacific Information Technology Conference (APIT 2023)',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 10, 2023 13:00:00'),
        start: new Date('January 10, 2023 16:00:00'),
        title: 'Effective Procurement Operations - Improve Purchasing Efficiency',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 18, 2023 20:00:00'),
        start: new Date('January 18, 2023 20:20:00'),
        title: 'Mindfulness Meditation: Wednesday Pause - Ho Chi Minh',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 15, 2023 13:00:00'),
        start: new Date('January 15, 2023 16:00:00'),
        title: 'Second Session with Alex Stan',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('January 31, 2023 19:00:00'),
        start: new Date('January 31, 2023 20:30:00'),
        title: 'Crafting Content for Social Media',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('March 1, 2023 10:00:00'),
        start: new Date('March 1, 2023 11:30:00'),
        title: 'TikTok for Small Business',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date(),
        start: new Date(),
        title: 'SBA Federal Small Business Certifications Workshop WEBINAR',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date(),
        start: new Date(),
        title: 'Social media for your small business: Webinar',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date(),
        start: new Date(),
        title: 'Digital & Social Media Marketing Webinar',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('June 1, 2023 19:00:00'),
        start: new Date('June 1, 2023 20:30:00'),
        title: 'How To Do Webinars',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('April 3, 2023 12:00:00'),
        start: new Date('April 3, 2023 16:30:00'),
        title: 'Online presence for growing your small business: Webinar',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 23, 2023 19:00:00'),
        start: new Date('February 23, 2023 20:30:00'),
        title: 'Facebook and Instagram Advertising on a Small Budget',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 25, 2023 19:00:00'),
        start: new Date('February 25, 2023 20:30:00'),
        title: 'How to Launch an E-Commerce Site That Grows With You',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 2, 2023 10:00:00'),
        start: new Date('February 2, 2023 11:30:00'),
        title: 'WEBINAR Digital Tools, Software & Apps to Efficiently Manage Your Small Biz',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 25, 2023 19:00:00'),
        start: new Date('February 25, 2023 20:30:00'),
        title: 'How to Launch an E-Commerce Site That Grows With You',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 21, 2023 10:00:00'),
        start: new Date('February 21, 2023 11:30:00'),
        title: 'Google Ads for Small Business',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
    {
        id: randomId(len, pattern),
        allDay: false,
        end: new Date('February 8, 2023 19:00:00'),
        start: new Date('February 8, 2023 20:30:00'),
        title: 'How to Drive More Traffic To Your Website',
        url: 'http://dummyurl.com',
        img: clientImg,
        clientLink: 'http://dummyurl.com',
        type: 'webinar'
    },
]